// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0zYpiiTEMFUjyVM9GB9QgWfdODUCTqaM',
    appId: '1:905055791351:web:2d96a96cd0a5a49aa88bf2',
    messagingSenderId: '905055791351',
    projectId: 'prj2026-mdp-f8e32',
    authDomain: 'prj2026-mdp-f8e32.firebaseapp.com',
    storageBucket: 'prj2026-mdp-f8e32.firebasestorage.app',
    measurementId: 'G-TP2GK6JVV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBemDRAKdK57MPJLykR8LqtnLPCy7WOAkA',
    appId: '1:905055791351:android:00b60f83167f2e2ba88bf2',
    messagingSenderId: '905055791351',
    projectId: 'prj2026-mdp-f8e32',
    storageBucket: 'prj2026-mdp-f8e32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe92Hl0XAB1mm4aUJA3mwQt_zDj8ULDgw',
    appId: '1:905055791351:ios:64bf3338fbce6075a88bf2',
    messagingSenderId: '905055791351',
    projectId: 'prj2026-mdp-f8e32',
    storageBucket: 'prj2026-mdp-f8e32.firebasestorage.app',
    iosClientId: '905055791351-9gpgrcrvoco2ian4ql912p580j1s5oui.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe92Hl0XAB1mm4aUJA3mwQt_zDj8ULDgw',
    appId: '1:905055791351:ios:64bf3338fbce6075a88bf2',
    messagingSenderId: '905055791351',
    projectId: 'prj2026-mdp-f8e32',
    storageBucket: 'prj2026-mdp-f8e32.firebasestorage.app',
    iosClientId: '905055791351-9gpgrcrvoco2ian4ql912p580j1s5oui.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0zYpiiTEMFUjyVM9GB9QgWfdODUCTqaM',
    appId: '1:905055791351:web:1f2b1918da59560da88bf2',
    messagingSenderId: '905055791351',
    projectId: 'prj2026-mdp-f8e32',
    authDomain: 'prj2026-mdp-f8e32.firebaseapp.com',
    storageBucket: 'prj2026-mdp-f8e32.firebasestorage.app',
    measurementId: 'G-RKEF6Z4D1Q',
  );
}
